### ISSUE TITLE
Work on first arrow enchantment behaviour (flame)

### ISSUE THREAD

**Issue by FubyCutie** [SkyeEmmyMods/CarpetEnhancedDispensers#4]

**Comment by FubyCutie** [comment]
The dispenser behaviour I believe will be best handled by a system where you can map an enchantment, to something that handles the behaviour. We can create an interface for the behaviour, that can be implemented by each desired enchantment effect, where it will then add itself to a map of all behaviours, which can be used to invoke them when the dispenser fires

**Comment by FubyCutie** [comment]
Check how these enchantments are done with bows, is it calculated when the arrow hits? Or when it is fired? Do we need to make a mixin to do with the arrow damage to have this? Maybe not flame, but maybe power?

**Comment by FubyCutie** [comment]
Scope has been changed for v1, this issue only relates to flame now

**Comment by EmiliaThorsen** [comment]
implemented in this commmit https://github.com/SkyeEmmyMods/CarpetEnhancedDispensers/commit/3766255c8ebbfb8c93d7a41cfc4f9e5fc632cab5
